{{- if .Values.redis.inCluster }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.host }}
  namespace: {{ .Values.namespace.name | default "maito-prod" }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: maito-platform
spec:
  serviceName: {{ .Values.redis.host }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
            - --appendonly
            - "yes"
            - --requirepass
            - $(REDIS_PASSWORD)
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "maito.fullname" . }}-secret
                  key: SPRING_REDIS_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.redis.storageClass }}
        storageClassName: {{ .Values.redis.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.storageSize }}
{{- end }}
