apiVersion: v1
kind: ConfigMap
metadata:
  name: maito-monolith-config
  namespace: maito-prod
  labels:
    app.kubernetes.io/name: maito-monolith
    app.kubernetes.io/part-of: maito-platform
data:
  SPRING_PROFILES_ACTIVE: "prod"
  MAITO_RATE_LIMITING_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus,tenants"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.maito-prod.svc.cluster.local:5432/maito_db"
  SPRING_DATASOURCE_USERNAME: "maito_user"
  SPRING_REDIS_HOST: "redis.maito-prod.svc.cluster.local"
  SPRING_REDIS_PORT: "6379"
  SPRING_ELASTICSEARCH_URIS: "http://elasticsearch.maito-prod.svc.cluster.local:9200"
  ZIPKIN_ENDPOINT: "http://tempo.monitoring.svc.cluster.local:9411/api/v2/spans"
