apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "maito.fullname" . }}-config
  namespace: {{ .Values.namespace.name | default "maito-prod" }}
  labels:
    {{- include "maito.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
  MAITO_RATE_LIMITING_ENABLED: {{ .Values.env.MAITO_RATE_LIMITING_ENABLED | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus,tenants"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresql.user | quote }}
  SPRING_REDIS_HOST: {{ .Values.redis.host | quote }}
  SPRING_REDIS_PORT: {{ .Values.redis.port | quote }}
  SPRING_ELASTICSEARCH_URIS: "http://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
  ZIPKIN_ENDPOINT: {{ .Values.env.ZIPKIN_ENDPOINT | quote }}
